<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>Loopstructor.AutoPlayer.Core</AssemblyName>
    <RootNamespace>Loopstructor.AutoPlayer.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
