<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>Loopstructor.AutoPlayer.Updater</AssemblyName>
    <RootNamespace>Loopstructor.AutoPlayer.Updater</RootNamespace>
    <ApplicationIcon>..\..\assets\branding\manager.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Verification\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Verification" />
    <InternalsVisibleTo Include="Loopstructor.AutoPlayer.Tests" />
  </ItemGroup>
</Project>
